name: MyWorkflow

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
    myfirstjob:
        name: First job
        runs-on: ubuntu-latest
        steps:
        - name: Step one
          uses: actions/checkout@v3
        - name: Step Two
          run:  |
            touch newfile.yaml
            echo "Hello world" >> newfile.yaml
            cat newfile.yaml
            pwd
            
    mysecondjob:
        needs: [myfirstjob]
        name: Second job
        runs-on: macos-latest
        steps:
        - name: Step date
          run: date
          
            
    mythirdjob:
        name: Third job
        runs-on: macos-latest
        steps:
        - name: Step date
          run: date

